import Wrapper from "@/Components/Wrapper/Wrapper";
import "./globals.css";

export const metadata = {
  title: "Task-Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning >
        <Wrapper>
          {children}
        </Wrapper>
      </body>
    </html>
  );
}
